name: Build

on:
  push:
    branches: '**'
    tags-ignore: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Install pnpm dependencies
      run: pnpm install
    - name: Build
      run: pnpm build